### ISSUE TITLE
<+context+> conflicts with command start from `

### ISSUE THREAD

**Issue by duguyipiao** [vim-latex/vim-latex#102]
How to reproduce?

1. Type EEQ, the result is
```tex
\begin{equation}
	<+content+>
	\label{<+label+>}
\end{equation}<++>
```
and the cursor is in `<+content+>`
2. Type `a

Excepted result:
```tex
\begin{equation}
	\alpha
	\label{<+label+>}
\end{equation}<++>
```

Real result:
After type `` ` ``, command line says ``Enter map:` ``

**Comment by gerw** [comment]
After `EEQ`, `<+content+>` is highlighted and you are in select-mode (by using the default settings). Hence, the standard visual-maps apply (which might be considered a bug or a feature). However, `` `a`` is an insert-mode mapping.

However, I think I share your point of view and this is an error. I will change the definition of the visual mappings to use `xmap` (applies only to visual mode) instead of `vmap` (applies to visual and select mode).

**Comment by gerw** [comment]
Does the fix work for you?

**Comment by duguyipiao** [comment]
Thanks a lot for the fix. It works.
