### ISSUE TITLE
Cite autocompletion problem

### ISSUE THREAD

**Issue by leosenko** [vim-latex/vim-latex#112]
After writing `\cite{` and pressing `F9`, the screen gets split into 3 windows, see at the bottom. When I go to any entry in the middle window and hit `Enter` I get back to the tex file without cite being completed.
This is vim-gtk3 debian stretch packcage built with python3 support but not python2 support
```
:echo Tex_UsePython
1
:echo Tex_GetVarValue('Tex_UseCiteCompletionVer2')
1
:echo Tex_GetVarValue('Tex_UsePython')
1
```

Further autocompletion works for anything with `\label` only citations do not work.

Any ideas what is wrong?
![gvim](https://user-images.githubusercontent.com/3658579/33344079-a8740426-d455-11e7-926c-f244f2ba005d.png)

**Comment by gerw** [comment]
What do
````
:echo Tex_HasPython
:echo Tex_UsePython()
````
say? Can you enable debugging
````
let g:Tex_Debug = 1
let g:Tex_DebugLog = "vim-latex-suite.log"
````
and show the log file after trying to complete a `\cite{`?

**Comment by leosenko** [comment]
Both commands return:
```
E121: Undefined variable: Tex_HasPython
E15: Invalid expression: Tex_HasPython
```

I do not know why. On the other hand:
`echo Tex_UsePython`
(without the parentheses) returns `1` 

Also, shouldn't I get only two buffers instead of three after `F9`?

The contents of the log file:

```
view : Tex_Complete: s:type = cite, typeoption = 
view : :Tex_Complete: using s:prefix = 
proj : texproject.vim: catching LatexSuiteFileType event
proj : Tex_ProjectLoad: sourcing [/home/user/path/main.tex.latexmain]
env : envmacros.vim: Catching LatexSuiteFileType event
comp : compiler.vim: Catching LatexSuiteFileType event
fold : folding.vim: catching LatexSuiteFileType
brak : brackets.vim: Catching LatexSuiteFileType event
view : texviewer.vim: Catching LatexSuiteFileType event
main : main.vim: Catching LatexSuiteFileType event
pack : packages.vim: Catching LatexSuiteFileType event
pack : +Tex_pack_updateall
view : +Tex_ScanFileForCite: searching for bibkeys in main.tex (buffer #2)
proj : texproject.vim: catching LatexSuiteFileType event
proj : Tex_ProjectLoad: sourcing [/home/user/path/main.tex.latexmain]
env : envmacros.vim: Catching LatexSuiteFileType event
comp : compiler.vim: Catching LatexSuiteFileType event
fold : folding.vim: catching LatexSuiteFileType
brak : brackets.vim: Catching LatexSuiteFileType event
view : texviewer.vim: Catching LatexSuiteFileType event
main : main.vim: Catching LatexSuiteFileType event
pack : packages.vim: Catching LatexSuiteFileType event
pack : +Tex_pack_updateall
view : scanning recursively in [sec1.tex]
view : +Tex_ScanFileForCite: searching for bibkeys in sec1.tex (buffer #4)
view : scanning recursively in [sec2.tex]
view : +Tex_ScanFileForCite: searching for bibkeys in sec2.tex (buffer #1)
proj : texproject.vim: catching LatexSuiteFileType event
proj : Tex_ProjectLoad: sourcing [/home/user/path/main.tex.latexmain]
env : envmacros.vim: Catching LatexSuiteFileType event
comp : compiler.vim: Catching LatexSuiteFileType event
fold : folding.vim: catching LatexSuiteFileType
brak : brackets.vim: Catching LatexSuiteFileType event
view : texviewer.vim: Catching LatexSuiteFileType event
main : main.vim: Catching LatexSuiteFileType event
pack : packages.vim: Catching LatexSuiteFileType event
pack : +Tex_pack_updateall
view : scanning recursively in [bib.tex]
view : +Tex_ScanFileForCite: searching for bibkeys in bib.tex (buffer #5)
view : Tex_ScanFileForCite: found bibliography command in bib.tex
view : trying to search through [../pathtoref/ref]
view : finding .bib file [bib.tex]
view : +Tex_SetupCWindow
view : +Tex_SyncPreviewWindow
view : :Tex_CompleteRefCiteCustom: completing with 
view : :Tex_SwitchToInsertMode: 
```

**Comment by gerw** [comment]
This is weird. The variable `Tex_HasPython` is defined in https://github.com/vim-latex/vim-latex/blob/master/ftplugin/latex-suite/main.vim#L922. Which version of latex-suite are you using? Can you try to figure out why `Tex_HasPython` is not set?

Is there an error popping up after pressing `F9`, which immediately gets overlayed by the completion windows?

**Comment by leosenko** [comment]
I do not have those lines in the file at all. There seems to be no error after pressing `F9` or it is beyond my eye recognition.
How do I find the version of latex-suite? I looked at some .vim files belonging to latex-suite but there was no version info.

**Comment by gerw** [comment]
The source code does not include a reliable version information. How do you installed latex-suite? Your version seems to be outdated (i.e., no python3 support). Please update your installation to the master-branch.

**Comment by leosenko** [comment]
I upgraded to the 1.9 which is at sourceforge and I remember why I should have not done that. The issue with the new version is that it enforces folding which I have no idea how to disable. The standard vim way are disregarded. This problem aside, now after pressin `F9` after `\cite{` absolutely nothing happens. On the other hand:
```
:echo Tex_HasPython
3
:echo Tex_UsePython()
1
```
and the log file as you suggested above:

```
view : Tex_Complete: s:type = cite, typeoption = 
view : :Tex_Complete: using s:prefix = 
view : :Tex_FindBibFiles: 
proj : texproject.vim: catching LatexSuiteFileType event
proj : Tex_ProjectLoad: sourcing [/home/user/path/main.tex.latexmain]
env : envmacros.vim: Catching LatexSuiteFileType event
comp : compiler.vim: Catching LatexSuiteFileType event
fold : folding.vim: catching LatexSuiteFileType
brak : brackets.vim: Catching LatexSuiteFileType event
view : texviewer.vim: Catching LatexSuiteFileType event
main : main.vim: Catching LatexSuiteFileType event
pack : packages.vim: Catching LatexSuiteFileType event
pack : +Tex_pack_updateall
view : :Tex_SwitchToInsertMode: 
```

**Comment by gerw** [comment]
Please use the version from this git repository. V1.9 is one year old (and imho it does not contain the fix you need).

Folding can be disabled by using `let g:Tex_Folding = 0` in `.vim/ftplugins/tex.vim`.

Finally, completion with F9 does not work since latex-suite cannot find a bib-file. Can you show your tex-file?

**Comment by leosenko** [comment]
I did the update. 
`main.tex`
```
\documentclass[a4paper,12pt,twoside]{article}
\usepackage[a4paper,includeheadfoot,margin=2.5cm]{geometry}
\usepackage[utf8]{inputenc}
\usepackage{graphicx}
\usepackage{hyperref}
\begin{document}
\input{sec1}
\input{bib}
\end{document}
```
`sec1.tex`
`This is a test. This is a test. \cite{DeMeo2013}`

`bib.tex`
```
\bibliographystyle{apalike}
\bibliography{ref}

```
The log file:
```
view : Tex_Complete: s:type = cite, typeoption = 
view : :Tex_Complete: using s:prefix = 
view : :Tex_FindBibFiles: 
proj : texproject.vim: catching LatexSuiteFileType event
proj : Tex_ProjectLoad: sourcing [/home/user/test/main.tex.latexmain]
env : envmacros.vim: Catching LatexSuiteFileType event
comp : compiler.vim: Catching LatexSuiteFileType event
fold : folding.vim: catching LatexSuiteFileType
SyntaxFolds : Finished folding in   0.017270 seconds.
brak : brackets.vim: Catching LatexSuiteFileType event
view : texviewer.vim: Catching LatexSuiteFileType event
main : main.vim: Catching LatexSuiteFileType event
main : SetTeXOptions: sourcing maps
comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Compiler
comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Viewr
comp : compiler/tex.vim: sourcing this file
pack : packages.vim: Catching LatexSuiteFileType event
pack : +Tex_pack_updateall
view : :Tex_FindBibFiles: returning []
view : :Tex_StartCiteCompletion: No bibfiles found.
view : :Tex_SwitchToInsertMode: 
```
The directory contents

![image](https://user-images.githubusercontent.com/3658579/33433960-acb6f58c-d5ab-11e7-9f34-6630573cd139.png)

the complete files:
[test.tar.gz](https://github.com/vim-latex/vim-latex/files/1517987/test.tar.gz)

**Comment by gerw** [comment]
Currently, the bibliography command cannot be in an inputted file. It must be in the main tex file.

-------- Ursprüngliche Nachricht --------
Von: leosenko <notifications@github.com> 
Datum: 30.11.17  14:53  (GMT+01:00) 
An: vim-latex/vim-latex <vim-latex@noreply.github.com> 
Cc: Gerd Wachsmuth <gerd.wachsmuth@mathematik.tu-chemnitz.de>, Comment <comment@noreply.github.com> 
Betreff: Re: [vim-latex/vim-latex] Cite autocompletion problem (#112) 

I did the update.

main.tex
\documentclass[a4paper,12pt,twoside]{article}
\usepackage[a4paper,includeheadfoot,margin=2.5cm]{geometry}
\usepackage[utf8]{inputenc}
\usepackage{graphicx}
\usepackage{hyperref}
\begin{document}
\input{sec1}
\input{bib}
\end{document}

sec1.tex

This is a test. This is a test. \cite{DeMeo2013}
bib.tex
\bibliographystyle{apalike}
\bibliography{ref}


The log file:
view : Tex_Complete: s:type = cite, typeoption = 
view : :Tex_Complete: using s:prefix = 
view : :Tex_FindBibFiles: 
proj : texproject.vim: catching LatexSuiteFileType event
proj : Tex_ProjectLoad: sourcing [/home/user/test/main.tex.latexmain]
env : envmacros.vim: Catching LatexSuiteFileType event
comp : compiler.vim: Catching LatexSuiteFileType event
fold : folding.vim: catching LatexSuiteFileType
SyntaxFolds : Finished folding in   0.017270 seconds.
brak : brackets.vim: Catching LatexSuiteFileType event
view : texviewer.vim: Catching LatexSuiteFileType event
main : main.vim: Catching LatexSuiteFileType event
main : SetTeXOptions: sourcing maps
comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Compiler
comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Viewr
comp : compiler/tex.vim: sourcing this file
pack : packages.vim: Catching LatexSuiteFileType event
pack : +Tex_pack_updateall
view : :Tex_FindBibFiles: returning []
view : :Tex_StartCiteCompletion: No bibfiles found.
view : :Tex_SwitchToInsertMode: 

The directory contents

the complete files:

test.tar.gz

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/vim-latex/vim-latex","title":"vim-latex/vim-latex","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/vim-latex/vim-latex"}},"updates":{"snippets":[{"icon":"PERSON","message":"@leosenko in #112: I did the update. \r\n`main.tex`\r\n```\r\n\\documentclass[a4paper,12pt,twoside]{article}\r\n\\usepackage[a4paper,includeheadfoot,margin=2.5cm]{geometry}\r\n\\usepackage[utf8]{inputenc}\r\n\\usepackage{graphicx}\r\n\\usepackage{hyperref}\r\n\\begin{document}\r\n\\input{sec1}\r\n\\input{bib}\r\n\\end{document}\r\n```\r\n`sec1.tex`\r\n`This is a test. This is a test. \\cite{DeMeo2013}`\r\n\r\n`bib.tex`\r\n```\r\n\\bibliographystyle{apalike}\r\n\\bibliography{ref}\r\n\r\n```\r\nThe log file:\r\n```\r\nview : Tex_Complete: s:type = cite, typeoption = \r\nview : :Tex_Complete: using s:prefix = \r\nview : :Tex_FindBibFiles: \r\nproj : texproject.vim: catching LatexSuiteFileType event\r\nproj : Tex_ProjectLoad: sourcing [/home/user/test/main.tex.latexmain]\r\nenv : envmacros.vim: Catching LatexSuiteFileType event\r\ncomp : compiler.vim: Catching LatexSuiteFileType event\r\nfold : folding.vim: catching LatexSuiteFileType\r\nSyntaxFolds : Finished folding in   0.017270 seconds.\r\nbrak : brackets.vim: Catching LatexSuiteFileType event\r\nview : texviewer.vim: Catching LatexSuiteFileType event\r\nmain : main.vim: Catching LatexSuiteFileType event\r\nmain : SetTeXOptions: sourcing maps\r\ncomp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Compiler\r\ncomp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Viewr\r\ncomp : compiler/tex.vim: sourcing this file\r\npack : packages.vim: Catching LatexSuiteFileType event\r\npack : +Tex_pack_updateall\r\nview : :Tex_FindBibFiles: returning []\r\nview : :Tex_StartCiteCompletion: No bibfiles found.\r\nview : :Tex_SwitchToInsertMode: \r\n```\r\nThe directory contents\r\n\r\n![image](https://user-images.githubusercontent.com/3658579/33433960-acb6f58c-d5ab-11e7-9f34-6630573cd139.png)\r\n\r\nthe complete files:\r\n[test.tar.gz](https://github.com/vim-latex/vim-latex/files/1517987/test.tar.gz)"}],"action":{"name":"View Issue","url":"https://github.com/vim-latex/vim-latex/issues/112#issuecomment-348193870"}}}

**Comment by leosenko** [comment]
Regarding the folding, in my installation the `tex.vim` ftplugin is in `/usr/share/vim/vim80/ftplugin/tex.vim` and thus requires root permissions to edit, and even if I added the last line `let g:Tex_Folding = 0`, the folding is still on when I open any tex file. I don't think the system vim plugin needs to be modified as this behaviour changed after updating vim-latex suite which resides in `~/.vim`

**Comment by gerw** [comment]
You should not edit the system file, but the file `~/.vim/ftplugin/tex.vim`.

**Comment by f-dj** [comment]
Sorry for this late addition, but I don't think that is correct as I made it work. One must only disable the use of python completely for vim latex, using `let g:Tex_UsePython = 0` in vimrc.

Now I don't know if this impacts performance or other features, but it makes the completion work also in inputted files, which I find very important.

Since it has been more than 2 years,  why is this still not documented? Also, it should be highlighted that this is a python specific issue, as opposed to being not possible "currently" (i.e. 2 years ago). Is it possible to contribute to the documentation? I would be happy to do so. This issue frustrated me for hours and I don't think this old github issue here is enough documentation. 

From [the docs:](http://vim-latex.sourceforge.net/documentation/latex-suite/latex-completion-cite.html)
> Firstly, if the present file has a master-file defined for it, then Latex-Suite will perform the following steps on that file instead of on the current file. 

That directly contradicts what you said about it not working currently. I am slightly confused about what to think now.

This is really a great project but it does so much damage if important features like this feel "broken" when using the first time. If the docs contradict the actual behaviour, it's a problem.

> Currently, the bibliography command cannot be in an inputted file. It must be in the main tex file.
> […](#)
> -------- Ursprüngliche Nachricht -------- Von: leosenko <notifications@github.com> Datum: 30.11.17 14:53 (GMT+01:00) An: vim-latex/vim-latex <vim-latex@noreply.github.com> Cc: Gerd Wachsmuth <gerd.wachsmuth@mathematik.tu-chemnitz.de>, Comment <comment@noreply.github.com> Betreff: Re: [vim-latex/vim-latex] Cite autocompletion problem (#112) I did the update. main.tex \documentclass[a4paper,12pt,twoside]{article} \usepackage[a4paper,includeheadfoot,margin=2.5cm]{geometry} \usepackage[utf8]{inputenc} \usepackage{graphicx} \usepackage{hyperref} \begin{document} \input{sec1} \input{bib} \end{document} sec1.tex This is a test. This is a test. \cite{DeMeo2013} bib.tex \bibliographystyle{apalike} \bibliography{ref} The log file: view : Tex_Complete: s:type = cite, typeoption = view : :Tex_Complete: using s:prefix = view : :Tex_FindBibFiles: proj : texproject.vim: catching LatexSuiteFileType event proj : Tex_ProjectLoad: sourcing [/home/user/test/main.tex.latexmain] env : envmacros.vim: Catching LatexSuiteFileType event comp : compiler.vim: Catching LatexSuiteFileType event fold : folding.vim: catching LatexSuiteFileType SyntaxFolds : Finished folding in 0.017270 seconds. brak : brackets.vim: Catching LatexSuiteFileType event view : texviewer.vim: Catching LatexSuiteFileType event main : main.vim: Catching LatexSuiteFileType event main : SetTeXOptions: sourcing maps comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Compiler comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Viewr comp : compiler/tex.vim: sourcing this file pack : packages.vim: Catching LatexSuiteFileType event pack : +Tex_pack_updateall view : :Tex_FindBibFiles: returning [] view : :Tex_StartCiteCompletion: No bibfiles found. view : :Tex_SwitchToInsertMode: The directory contents the complete files: test.tar.gz — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/vim-latex/vim-latex","title":"vim-latex/vim-latex","subtitle":"GitHub repository","main_image_url":"[https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open](https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png%22,%22avatar_image_url%22:%22https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png%22,%22action%22:%7B%22name%22:%22Open) in GitHub","url":"[https://github.com/vim-latex/vim-latex"}},"updates":{"snippets":[{"icon":"PERSON","message":"@leosenko](https://github.com/vim-latex/vim-latex%22%7D%7D,%22updates%22:%7B%22snippets%22:%5B%7B%22icon%22:%22PERSON%22,%22message%22:%22@leosenko) in #112: I did the update. \r\n`main.tex`\r\n```\r\n\\documentclass[a4paper,12pt,twoside]{article}\r\n\\usepackage[a4paper,includeheadfoot,margin=2.5cm]{geometry}\r\n\\usepackage[utf8]{inputenc}\r\n\\usepackage{graphicx}\r\n\\usepackage{hyperref}\r\n\\begin{document}\r\n\\input{sec1}\r\n\\input{bib}\r\n\\end{document}\r\n```\r\n`sec1.tex`\r\n`This is a test. This is a test. \\cite{DeMeo2013}`\r\n\r\n`bib.tex`\r\n```\r\n\\bibliographystyle{apalike}\r\n\\bibliography{ref}\r\n\r\n```\r\nThe log file:\r\n```\r\nview : Tex_Complete: s:type = cite, typeoption = \r\nview : :Tex_Complete: using s:prefix = \r\nview : :Tex_FindBibFiles: \r\nproj : texproject.vim: catching LatexSuiteFileType event\r\nproj : Tex_ProjectLoad: sourcing [/home/user/test/main.tex.latexmain]\r\nenv : envmacros.vim: Catching LatexSuiteFileType event\r\ncomp : compiler.vim: Catching LatexSuiteFileType event\r\nfold : folding.vim: catching LatexSuiteFileType\r\nSyntaxFolds : Finished folding in 0.017270 seconds.\r\nbrak : brackets.vim: Catching LatexSuiteFileType event\r\nview : texviewer.vim: Catching LatexSuiteFileType event\r\nmain : main.vim: Catching LatexSuiteFileType event\r\nmain : SetTeXOptions: sourcing maps\r\ncomp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Compiler\r\ncomp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Viewr\r\ncomp : compiler/tex.vim: sourcing this file\r\npack : packages.vim: Catching LatexSuiteFileType event\r\npack : +Tex_pack_updateall\r\nview : :Tex_FindBibFiles: returning []\r\nview : :Tex_StartCiteCompletion: No bibfiles found.\r\nview : :Tex_SwitchToInsertMode: \r\n```\r\nThe directory contents\r\n\r\n![image]([https://user-images.githubusercontent.com/3658579/33433960-acb6f58c-d5ab-11e7-9f34-6630573cd139.png)\r\n\r\nthe](https://user-images.githubusercontent.com/3658579/33433960-acb6f58c-d5ab-11e7-9f34-6630573cd139.png)%5Cr%5Cn%5Cr%5Cnthe) complete files:\r\n[test.tar.gz]([https://github.com/vim-latex/vim-latex/files/1517987/test.tar.gz)"}],"action":{"name":"View](https://github.com/vim-latex/vim-latex/files/1517987/test.tar.gz)%22%7D%5D,%22action%22:%7B%22name%22:%22View) Issue","url":"[#112 (comment)](https://github.com/vim-latex/vim-latex/issues/112#issuecomment-348193870)"}}}

**Comment by f-dj** [comment]
I know it's an old issue, but that is not entirely true.

This is a specific limitation of the python libraries coming with `vim-latex`. How do I know? I put `let g:Tex_UsePython = 0` in `.vimrc` and....it works! 

Is it possible to contribute to the documentation? After more than two years it is still undocumented, so I think this should be changed. 

Also, I think it should be seen as a bug, not something not implemented yet. Everything that works without python should work with python. That's how the docs make it sound [here](http://vim-latex.sourceforge.net/documentation/latex-suite/ls-general-purpose-settings.html).

**Comment by gerw** [comment]
If you use `let g:Tex_UsePython = 0`, then vim-latex uses an entirely different strategy to complete the cite completion. The same can be accomplished with `let g:Tex_UseCiteCompletionVer2 = 0`.

Feel free to contribute to the documentation.

**Comment by gerw** [comment]
I have just pushed a small patch which allows for `\bibliography`-commands in included files also with the python-version of the bib completion. Please have a look.

Note that the online documentation is out-of-date (I cannot modify it).

**Comment by f-dj** [comment]
Wow thanks a lot for your help! I did not expect a quick answer on an old issue let alone a patch. I'll check it out later after work if it works for me.

As for the contribution on the doc in general: is there any repos where pull requests can be created? 

> I have just pushed a small patch which allows for `\bibliography`-commands in included files also with the python-version of the bib completion. Please have a look.
> 
> Note that the online documentation is out-of-date (I cannot modify it).

**Comment by gerw** [comment]
The documentation is in this repository, see https://github.com/vim-latex/vim-latex/blob/master/doc/latex-suite.xml

There is also a `Makefile` allowing to create the vim documentation and an html version.
