### ISSUE TITLE
[Alt]-i produces é instead of \item in list

### ISSUE THREAD

**Issue by jarrndewitt** [vim-latex/vim-latex#115]
I am using a current vim-latex installation with vim 8.0 (with cream) on windows 10.

When I press [Alt]-i inside a list environment I receive an "é" instead of the expected "\item".

**Comment by gerw** [comment]
The default behavior of latex-suite has changed one year ago, see https://github.com/vim-latex/vim-latex/commit/8df6178f40350ea1a6448ea2aacc332eb395ad99.

You can reenable the old behavior by `let g:Tex_AdvancedMath = 1` in your `~/.vim/ftplugin/tex.vim`, see also `:help altkey-mapping`.

The main problem is that vim is not able to distinguish between `Alt+i` and `é`. That is, with the old behavior of latex-suite one receives `\item` instead of the expected `é`, and this is very annoying for people which have to use `é` often.
