### ISSUE TITLE
Some accented characters not displayed in insert mode

### ISSUE THREAD

**Issue by apinsard** [vim-latex/vim-latex#14]
In insert mode, some characters such as "é" or "â" are not taken into account.

One have to add the following line in a ~/.vim/ftplugin/tex.vim file for instance.

```
imap <buffer> <m-c> <Plug>Tex_InsertItemOnThisLine
```

We can now print "é" characters but still no "â".

**Comment by gerw** [comment]
There is some problem of vim with alt+key mappings. You could try to disable some mappings in `ftplugins/latex-suite/brackets.vim`, lines 128-133. Does this fix your issue?

(In my opinion, all alt-key mappings should be disabled by default, since many people are wondering why they cannot insert accented characters.)

**Comment by jmaibaum** [comment]
Having to quote from many French texts lately, I also came across this issue. I reckon that this is mainly an issue for people writing texts in languages other than English. At least for French this is certainly annoying, especially the "é" issue.

I can confirm that @apinsard's solution does work for "é", and that @gerw's suggestion to disable line 128 in `ftplugins/latex-suite/brackets.vim` brings back "â" in insert mode.

So I would add my vote to disable the alt-key mappings by default. That might upset people who have to write math formulas for not having their `\mathbf` etc. shortcuts, though. Perhaps it would be OK to disable the mappings only for insert mode, i.e. leaving them on in visual mode? Then people could insert accented characters in insert mode and modify their formulas in visual mode.

Testing some more accented characters, I also found that "ì" does not work, it turns into `\label{}<++>`. As I am not familiar with vim scripts and vim-latex's source code, I did not know where to look for. At least other latin vocals with ^, ´, and ` accents work. I did not test other accents.

**Comment by gerw** [comment]
As far as I understand the vim-behaviour is that all `Alt+key` mappings might be dangerous, since vim cannot distinguish between `Alt+key` or `accented character` (e.g., `é` has the same key-code as `Alt+c`). Hence, you can grep the code for mappings of `<M-...>`.

I would like to vote for the suggestion to disable all those mappings by default in insert-mode (and provide an option to enable them again).

**Comment by nowox** [comment]
This is a pretty old issue. I had it 10 years ago and it is very annoying each time I update my installation. I wish it will be fixed one day.
