### ISSUE TITLE
Error detected while processing function Tex_pack_supp_menu on osx

### ISSUE THREAD

**Issue by rubendibattista** [vim-latex/vim-latex#44]
Hello, 

I just installed vim-latex using Vundle on my OSX 10.11.3 but when I open a `.tex` file I receive the following error:

```
Error detected while processing function Tex_pack_supp_menu
Only one file name allowed: cd <path/to/file>
```

Any hints?

**Comment by gerw** [comment]
The error itself does not help - `cd` is not called within the function `Tex_pack_supp_menu`. You could try to enable some debugging:
    let g:Tex_Debug = 1
    let g:Tex_DebugLog = "vim-latex-suite.log"
(in `.vim/ftplugins/tex.vim`). Then, latex-suite should put a log file into the working directory.

Otherwise, you could disable the packages menu by `let g:Tex_PackagesMenu = 0` in your `.vim/ftplugins/tex.vim`.

**Comment by gerw** [comment]
Closed due to inactivity.
