### ISSUE TITLE
automatically yank <++> to clipboard

### ISSUE THREAD

**Issue by chantisnake** [vim-latex/vim-latex#47]
when insert for example `\frac{<+n+>}{<+d+>}` the `<+n+>` is automatically selected and when I starts typing the `<+n+>` goes away, which is nice.

The problem is the `<+n+>` when deleted is copied to clipboard too, any way that I can configure this.

**Comment by gerw** [comment]
This is caused by the select mode of vim. The latex-suite switches to select mode after inserting placeholders. The selected text is copied to the clipboard (officially the "unnamed register") after typing a key. This behaviour cannot be changed by the latex-suite.

However, you could set `let g:Imap_GoToSelectMode = 0` in your `~/.vimrc`. Then, latex-suite switches to visual mode instead of select mode and you can prevent the alternation of your clipboard.

Did this help?

**Comment by chantisnake** [comment]
I don't think so, I tried to put this variable in the vimrc, after C-j, it still goes to select mode.
![capture](https://cloud.githubusercontent.com/assets/10100995/14771100/441df5ae-0a4e-11e6-862e-9777b621cf0c.PNG)
![capture1](https://cloud.githubusercontent.com/assets/10100995/14771101/47db6e88-0a4e-11e6-8d04-9d17d08034b5.PNG)

I tried to find this variable, but I don't see this variable is used any where in vim latex, and cannot find the help of this variable in vim document.

I used vundle to install this plugin from the GitHub, is it because This GitHub repo is not up to date?

**Comment by gerw** [comment]
My fault. You could try to use https://github.com/gerw/vim-latex-suite/blob/master/plugin/imaps.vim instead of the `imaps.vim` provided from this repository. If this works for you, I will backport these changes to the official repository.

**Comment by chantisnake** [comment]
That works great! Thanks!

**Comment by gerw** [comment]
@chantisnake I have pushed the corresponding fix. Thank you for reporting!
