### ISSUE TITLE
IMAP cannot override

### ISSUE THREAD

**Issue by chantisnake** [vim-latex/vim-latex#50]
I tried to override the original EFI map:
```vim
call IMAP('EFI', '\begin{figure}[<+htpb+>]\<CR>\centering<CR>\includegraphics[height=2in]{<+eps file+>}<CR>\caption{<+caption text+>}<CR>\label{fig:<+label+>}<CR>\end{figure}<++>', '')
```
which does not work...

**Comment by chantisnake** [comment]
I just found out that predefined short cut cannot be override but user-defined can... I don't know why

**Comment by chantisnake** [comment]
https://github.com/vim-latex/vim-latex/blob/13e40aecdfc57c9a20484107a1447037800f7c44/ftplugin/latex-suite/envmacros.vim#L18

I found that this may related to the code here.

the 'IMAP' result is defined here:
https://github.com/vim-latex/vim-latex/blob/13e40aecdfc57c9a20484107a1447037800f7c44/ftplugin/latex-suite/envmacros.vim#L304

the IMAP is defined here;
github.com/vim-latex/vim-latex/blob/13e40aecdfc57c9a20484107a1447037800f7c44/ftplugin/latex-suite/envmacros.vim#L264

...
That is all I found... still no reason why it cannot be overridden...

maybe related to the definition of the IMAP function?

**Comment by gerw** [comment]
The problem is that the original mapping for EFI is defined via `IMAP('EFI', 'barfoo', 'tex')`, i.e., only for the tex-filetype. This overrules your mapping which is defined for all filetypes. Hence, you could do `IMAP('EFI','barfoo','tex')` to override the original mapping.

However, it is recommended (http://vim-latex.sourceforge.net/documentation/latex-suite/customizing-macros.html#Tex_Env_name) to use

    let g:Tex_Env_figure = "\\begin{figure}\<cr>..."

(You should also be careful with escaping the backslashes and line breaks.)
