### ISSUE TITLE
vim-latex remaps <S-Space>. How do I prevent this?

### ISSUE THREAD

**Issue by cristobaltapia** [vim-latex/vim-latex#86]
I have mapped ``<S-Space>`` as ``Esc`` and I really like it that way. Apparently, vim-latex remaps it to something else. Can this be disabled?

**Comment by cristobaltapia** [comment]
I think that was not the problem.

**Comment by cristobaltapia** [comment]
sorry... I think it is.

**Comment by gerw** [comment]
Yes, `vim-latex` imaps `<s-space>`, since there is an `IMAP`, see https://github.com/vim-latex/vim-latex/blob/master/ftplugin/latex-suite/main.vim#L157, and also https://github.com/vim-latex/vim-latex/blob/master/plugin/imaps.vim#L620.

One possible workaround is to put your imap into `.vim/after/ftplugin/tex.vim`. (Btw.: I have mapped the caps lock key to escape).


[A more sustainable solution would be to protect only those characters, for which an IMAP exists, instead of all characters between ASCII `32` and `127`.]

**Comment by cristobaltapia** [comment]
Thanks for the answer. Unfortunately, ``.vim/after/ftplugin/tex.vim`` did not work for me (using windows 7 here... not by choice :( ) 
Did you globally mapped caps lock to escape (i.e. in the OS), or within vimrc? 

And yes, maybe it would be better if to protect only the used characters.

**Comment by gerw** [comment]
Also on windows, there should be an `after` directory somewhere. Your usual tex-configuration should be in `some_directory/ftplugin/tex.vim` and then, this `after` directory is `some_directory/after/ftplugin/tex.vim`.

I mapped caps lock globally (in Linux and using xmodmap).

**Comment by cristobaltapia** [comment]
That's what I did: ``vimfiles/after/ftplugin/tex.vim``. Somehow it does not work.

I use this to map:
```
"Map <Esc> to Shift-Space.
inoremap <S-Space> <Esc>
vnoremap <S-Space> <Esc>
snoremap <S-Space> <Esc>
```
It does work in visual mode, though.

**Comment by gerw** [comment]
Sorry, you have to use `inoremap <buffer> <s-space> ...`, since the IMAP imaps are buffer-local. Does that work?

**Comment by cristobaltapia** [comment]
That was it! Thanks!

**Comment by gerw** [comment]
Glad to hear :)
